#### Hipparcos Star Astronomy Catalog

In [ ]:
# https://www.kaggle.com/code/cosmopablovd/hipparcos-eda

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('../datasets/hipparcos-voidmain.csv')
df.head()

,Catalog,HIP,Proxy,RAhms,DEdms,Vmag,VarFlag,r_Vmag,RAdeg,DEdeg,...,Survey,Chart,Notes,HD,BD,CoD,CPD,(V-I)red,SpType,r_SpType
0,H,1,NaN,00 00 00.22,+01 05 20.4,9.10,NaN,H,0.000912,1.089013,...,S,NaN,NaN,224700.0,B+00 5077,NaN,NaN,0.66,F5,S
1,H,2,NaN,00 00 00.91,-19 29 55.8,9.27,NaN,G,0.003797,-19.498837,...,NaN,NaN,NaN,224690.0,B-20 6688,NaN,NaN,1.04,K3V,4
2,H,3,NaN,00 00 01.20,+38 51 33.4,6.61,NaN,G,0.005008,38.859286,...,S,NaN,NaN,224699.0,B+38 5108,NaN,NaN,0.00,B9,S
3,H,4,NaN,00 00 02.01,-51 53 36.8,8.06,NaN,H,0.008382,-51.893546,...,S,NaN,NaN,224707.0,NaN,NaN,P-52 12237,0.43,F0V,2
4,H,5,NaN,00 00 02.39,-40 35 28.4,8.55,NaN,H,0.009965,-40.591224,...,NaN,NaN,NaN,224705.0,NaN,C-41 15372,P-41 9991,0.95,G8III,2

In [5]:
df.shape

(118218, 78)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118218 entries, 0 to 118217
Data columns (total 78 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Catalog    118218 non-null  object
 1   HIP        118218 non-null  int64
 2   Proxy      10925 non-null   object
 3   RAhms      118218 non-null  object
 4   DEdms      118218 non-null  object
 5   Vmag       118217 non-null  float64
 6   VarFlag    11562 non-null   float64
 7   r_Vmag     118217 non-null  object
 8   RAdeg      117955 non-null  float64
 9   DEdeg      117955 non-null  float64
 10  AstroRef   13734 non-null   object
 11  Plx        117955 non-null  float64
 12  pmRA       117955 non-null  float64
 13  pmDE       117955 non-null  float64
 14  e_RAdeg    117955 non-null  float64
 15  e_DEdeg    117955 non-null  float64
 16  e_Plx      117955 non-null  float64
 17  e_pmRA     117955 non-null  float64
 18  e_pmDE     117955 non-null  float64
 19  DE:RA      117955 non-null  float64
 20  Plx:RA     117955 non-null  float64
 21  Plx:DE     117955 non-null  float64
 22  pmRA:RA    117955 non-null  float64
 23  pmRA:DE    117955 non-null  float64
 24  pmRA:Plx   117955 non-null  float64
 25  pmDE:RA    117955 non-null  float64
 26  pmDE:DE    117955 non-null  float64
 27  pmDE:Plx   117955 non-null  float64
 28  pmDE:pmRA  117955 non-null  float64
 29  F1         117955 non-null  float64
 30  F2         116392 non-null  float64
 31  ---        118218 non-null  int64
 32  BTmag      114820 non-null  float64
 33  e_BTmag    114820 non-null  float64
 34  VTmag      114879 non-null  float64
 35  e_VTmag    114879 non-null  float64
 36  m_BTmag    12796 non-null   object
 37  B-V        116937 non-null  float64
 38  e_B-V      116937 non-null  float64
 39  r_B-V      116937 non-null  object
 40  V-I        116943 non-null  float64
 41  e_V-I      116943 non-null  float64
 42  r_V-I      118218 non-null  object
 43  CombMag    10783 non-null   object
 44  Hpmag      118204 non-null  float64
 45  e_Hpmag    118204 non-null  float64
 46  Hpscat     117247 non-null  float64
 47  o_Hpmag    117247 non-null  float64
 48  m_Hpmag    13211 non-null   object
 49  Hpmax      117247 non-null  float64
 50  HPmin      117247 non-null  float64
 51  Period     2541 non-null    float64
 52  HvarType   71622 non-null   object
 53  moreVar    8254 non-null    float64
 54  morePhoto  3581 non-null    object
 55  CCDM       19393 non-null   object
 56  n_CCDM     19393 non-null   object
 57  Nsys       19393 non-null   float64
 58  Ncomp      117955 non-null  float64
 59  MultFlag   17917 non-null   object
 60  Source     3236 non-null    object
 61  Qual       20835 non-null   object
 62  m_HIP      11101 non-null   object
 63  theta      11101 non-null   float64
 64  rho        11101 non-null   float64
 65  e_rho      11101 non-null   float64
 66  dHp        11101 non-null   float64
 67  e_dHp      11101 non-null   float64
 68  Survey     52045 non-null   object
 69  Chart      11653 non-null   object
 70  Notes      4178 non-null    object
 71  HD         98880 non-null   float64
 72  BD         73160 non-null   object
 73  CoD        27880 non-null   object
 74  CPD        40250 non-null   object
 75  (V-I)red   118218 non-null  float64
 76  SpType     115184 non-null  object
 77  r_SpType   115184 non-null  object
dtypes: float64(49), int64(2), object(27)
memory usage: 70.4+ MB

In [7]:
df.describe()

,HIP,Vmag,VarFlag,RAdeg,DEdeg,Plx,pmRA,pmDE,e_RAdeg,e_DEdeg,...,moreVar,Nsys,Ncomp,theta,rho,e_rho,dHp,e_dHp,HD,(V-I)red
count,118218.000000,118217.000000,11562.000000,117955.000000,117955.000000,117955.000000,117955.000000,117955.000000,117955.000000,117955.00000,...,8254.000000,19393.000000,117955.000000,11101.000000,11101.000000,11101.000000,11101.000000,11101.000000,98880.000000,118218.000000
mean,59176.745707,8.373233,1.739405,181.466380,-2.143250,7.215220,-1.303405,-16.599682,1.320787,1.10227,...,1.671432,1.193162,1.096452,181.245113,2.404513,0.019035,1.720967,0.160373,114374.227569,0.758321
std,34169.725917,1.312044,0.618728,103.261685,41.016397,11.286095,98.199404,93.859400,4.123088,3.43051,...,0.469721,0.418750,0.299403,104.910916,3.316871,0.021216,1.170635,0.252330,74189.731163,0.581249
min,1.000000,-1.440000,1.000000,0.000912,-89.782454,-54.950000,-4410.790000,-5813.000000,0.270000,0.33000,...,1.000000,1.000000,1.000000,0.000000,0.082000,0.001000,0.000000,0.010000,1.000000,-0.520000
25%,29581.250000,7.640000,1.000000,93.425334,-36.636503,2.510000,-15.150000,-21.740000,0.670000,0.59000,...,1.000000,1.000000,1.000000,92.000000,0.352000,0.005000,0.650000,0.030000,46735.750000,0.410000
50%,59177.500000,8.440000,2.000000,181.969874,-1.945926,4.610000,-1.680000,-5.650000,0.870000,0.72000,...,2.000000,1.000000,1.000000,183.000000,0.978000,0.011000,1.630000,0.070000,110373.500000,0.690000
75%,88767.750000,9.150000,2.000000,271.744455,31.435615,8.410000,11.840000,3.760000,1.170000,0.92000,...,2.000000,1.000000,1.000000,272.000000,3.050000,0.025000,2.700000,0.180000,175840.250000,1.040000
max,120416.000000,14.080000,3.000000,359.978792,89.569409,772.330000,6767.260000,10326.930000,281.160000,241.06000,...,2.000000,4.000000,4.000000,359.000000,23.588000,0.242000,4.470000,5.620000,358431.000000,9.290000

In [8]:
df.columns

Index(['Catalog', 'HIP', 'Proxy', 'RAhms', 'DEdms', 'Vmag', 'VarFlag',
       'r_Vmag', 'RAdeg', 'DEdeg', 'AstroRef', 'Plx', 'pmRA', 'pmDE',
       'e_RAdeg', 'e_DEdeg', 'e_Plx', 'e_pmRA', 'e_pmDE', 'DE:RA', 'Plx:RA',
       'Plx:DE', 'pmRA:RA', 'pmRA:DE', 'pmRA:Plx', 'pmDE:RA', 'pmDE:DE',
       'pmDE:Plx', 'pmDE:pmRA', 'F1', 'F2', '---', 'BTmag', 'e_BTmag', 'VTmag',
       'e_VTmag', 'm_BTmag', 'B-V', 'e_B-V', 'r_B-V', 'V-I', 'e_V-I', 'r_V-I',
       'CombMag', 'Hpmag', 'e_Hpmag', 'Hpscat', 'o_Hpmag', 'm_Hpmag', 'Hpmax',
       'HPmin', 'Period', 'HvarType', 'moreVar', 'morePhoto', 'CCDM', 'n_CCDM',
       'Nsys', 'Ncomp', 'MultFlag', 'Source', 'Qual', 'm_HIP', 'theta', 'rho',
       'e_rho', 'dHp', 'e_dHp', 'Survey', 'Chart', 'Notes', 'HD', 'BD', 'CoD',
       'CPD', '(V-I)red', 'SpType', 'r_SpType'],
      dtype='object')

In [9]:
df.duplicated().sum()

0

In [15]:
df['Period'].unique()

array([   nan, 327.5 ,   3.74, ..., 431.3 , 157.9 ,   7.75])

In [20]:
# Take a subsample of the dataset with some features
check_for_nan = df[["Plx","Vmag","r_Vmag","BTmag","VTmag","B-V","V-I","Hpmag","SpType","Period","HvarType","VarFlag"]]
check_for_nan.isnull().sum()

Plx            263
Vmag             1
r_Vmag           1
BTmag         3398
VTmag         3339
B-V           1281
V-I           1275
Hpmag           14
SpType        3034
Period      115677
HvarType     46596
VarFlag     106656
dtype: int64

In [21]:
# Memory usage
df.memory_usage( )

Index          128
Plx         945744
Vmag        945744
r_Vmag      945744
BTmag       945744
VTmag       945744
B-V         945744
V-I         945744
Hpmag       945744
SpType      945744
Period      945744
HvarType    945744
VarFlag     945744
dtype: int64

In [22]:
# Entries with the 10 largest Vmag
df.nlargest(10, "Vmag")

,Plx,Vmag,r_Vmag,BTmag,VTmag,B-V,V-I,Hpmag,SpType,Period,HvarType,VarFlag
70015,-20.09,14.08,H,NaN,NaN,NaN,NaN,14.1687,NaN,NaN,NaN,NaN
105199,NaN,13.78,H,NaN,NaN,NaN,NaN,13.9026,G0V,NaN,NaN,NaN
36618,NaN,13.64,H,NaN,NaN,NaN,NaN,13.7712,NaN,NaN,NaN,NaN
15547,-29.58,13.63,H,NaN,NaN,0.800,0.83,13.7850,NaN,NaN,NaN,NaN
71702,-0.82,13.61,H,NaN,NaN,-0.042,-0.02,13.6036,A0,NaN,NaN,NaN
58940,9.69,13.57,H,NaN,NaN,NaN,NaN,13.7670,NaN,NaN,D,NaN
105479,NaN,13.57,H,NaN,NaN,1.044,1.10,13.7083,NaN,NaN,NaN,NaN
78463,NaN,13.55,H,NaN,NaN,1.549,2.43,13.5803,NaN,NaN,NaN,NaN
109834,-9.99,13.52,H,NaN,NaN,1.410,1.76,13.6154,M2,NaN,NaN,NaN
102370,-2.20,13.51,H,NaN,NaN,NaN,NaN,13.6650,NaN,NaN,D,NaN